<?php
session_start();

require_once "../../../controllers/members.controller.php";
require_once "../../../models/members.model.php";

class printMembers{
public function getMembersPrinting(){ 

  $members = (new ControllerMember)->ctrShowRegularMemberList();

  require_once('tcpdf_include.php');
  $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $pdf->startPageGroup();
  $pdf->setPrintHeader(false);

  $cdn = date('F Y');
  $month = date("m");
  $year = date("Y");

  function getSundays($y,$m){ 
    $date = "$y-$m-01";
    $first_day = date('N',strtotime($date));
    $first_day = 7 - $first_day + 1;
    $last_day =  date('t',strtotime($date));
    $days = array();
    for($i=$first_day; $i<=$last_day; $i=$i+7 ){
        $days[] = $i;
    }
    return  $days;
  }

  $days = getSundays($year,$month);

  function fifthSunday($day){
    if(count($day) == 5){
      return $day[4];
    }else{
      return "";
    }
  }

  $fsunday = fifthSunday($days);
 



  $pdf->AddPage();
    $header = <<<EOF
    <div style="text-align:center; margin-bottom:-50px;"><img src="images/logo_circle.jpg" alt="clgf Logo" style="width:50px;" ></div>
    <table >
      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">CHIRST THE LIVING GOD FELLOWSHIP - HENARES</td> 
      </tr>

      <tr>
      <td style="width:540px;text-align:center;font-size:1em;font-weight:bold;">$cdn</td> 
    </tr>

      <tr>
        <td style="width:540px;text-align:center;font-size:10px;">Bacolod City</td> 
      </tr>  

      <tr>
       <td></td>
      </tr>
      <tr>
        <td></td>
      </tr>
  

      <tr >
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">LIST OF MEMBERS</td> 
      </tr> 
      <tr>
      <td></td>
    </tr>  

   

      <tr  style="width:25px; padding: 20px;">
        <td style="width:25px; "></td>

        <td style="border: 1px solid #202020;width: 170px; height:20px; text-align:center; font-size:1em; font-weight: bold;">NAME</td>
                                                            
        <td style="border: 1px solid 	#202020;width:80px; height:20px; text-align:center;  font-size:1em; font-weight: bold;">CATEGORY</td>   
        
        
        <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight:bold; background-color:#00d632;">$days[0]</td>  
        <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight:bold;">$days[1]</td> 
        <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight:bold;">$days[2]</td>  
        <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight:bold;">$days[3]</td>  
        <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight:bold;">$fsunday</td>  
      </tr>                        
    </table>
EOF;
    $pdf->writeHTML($header, false, false, false, false, '');
    

// ------------------------------------------------------------



  foreach ($members as $key => $value) {
    $fullname = $value["fullname"];
    $category = $value["category"];
   
      $content = <<<EOF
      <table>    
        <tr>
          <td style="width:25px;"></td>
          <td style="border: 1px solid #666; width:170px; text-align:center; font-size:0.9em; padding:50px;">$fullname</td>                                                             
          <td style="border: 1px solid #666; width: 80px; text-align:center; font-size:0.9em; padding:50px;">$category</td>     
          
          <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight: bold;"></td>  
          <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight: bold;"></td>  
          <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight: bold;"></td>  
          <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight: bold;"></td>  
          <td style="border: 1px solid 	#202020; width:48px; height:20px; text-align:center;  font-size:1em; font-weight: bold;"></td> 
        </tr>                
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');
    }

  $footer = <<<EOF
    <table style="border: none;">    
      <tr>
        <td></td>
      </tr>
      <tr>  
        <td style="width:505px;text-align:right;font-size:8px;">Generated by</td>
      </tr> 
      <tr>  
        <td style="width:505px;text-align:right;font-size:10px;">JAJAJO ENTERPRISE</td>
      </tr>                              
    </table>
EOF;
      $pdf->writeHTML($footer, false, false, false, false, '');     

    $pdf->Output('members_list.pdf', 'I');
   }
  }  

  $membersForm = new printMembers();
  $membersForm -> getMembersPrinting();
?>